# Generated by Django 3.0.2 on 2020-02-02 21:16

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=254, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.photos_upload_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('body', models.TextField(verbose_name='Comentário')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('accepted', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posts', verbose_name='Post relacionado')),
            ],
            options={
                'verbose_name': 'Blog Comentário',
                'verbose_name_plural': 'Blog Comentários',
                'ordering': ['date'],
            },
        ),
    ]
