# Generated by Django 3.0.2 on 2020-02-02 21:16

from django.db import migrations, models
import django.db.models.deletion
import layout.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='SubTítulo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('photo01', models.ImageField(upload_to=layout.models.photos_upload_path, verbose_name='Foto 01')),
                ('photo02', models.ImageField(upload_to=layout.models.photos_upload_path, verbose_name='Foto 02')),
                ('photo03', models.ImageField(upload_to=layout.models.photos_upload_path, verbose_name='Foto 03')),
                ('photo04', models.ImageField(upload_to=layout.models.photos_upload_path, verbose_name='Foto 04')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em ')),
            ],
            options={
                'verbose_name': 'Slide do Projeto',
                'verbose_name_plural': 'Slides dos Projetos',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=layout.models.photos_upload_path, verbose_name='Imagem')),
                ('client', models.CharField(max_length=100, verbose_name='Cliente')),
                ('architect', models.CharField(max_length=100, verbose_name='Arquiteto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em ')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='IntroSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('imageBackground', models.ImageField(upload_to=layout.models.photos_upload_path, verbose_name='Foto de fundo')),
                ('logo', models.ImageField(null=True, upload_to=layout.models.photos_upload_path, verbose_name='Logo')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Título')),
                ('route', models.CharField(blank=True, choices=[('blog', 'Blog'), ('produto', 'Produtos'), ('produtos', 'Loja')], default='Sem Rota', max_length=10, null=True, verbose_name='Rota')),
                ('link', models.BooleanField(default=False, verbose_name='Link')),
                ('posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Posts', verbose_name='Post')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Slide da introdução',
                'verbose_name_plural': 'Slides da introdução',
            },
        ),
    ]
