# Generated by Django 3.0.2 on 2020-02-02 21:16

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('sold', models.BooleanField(default=False, verbose_name='Vendido')),
                ('photo01', models.ImageField(upload_to=core.models.photos_upload_path, verbose_name='Foto 01')),
                ('photo02', models.ImageField(null=True, upload_to=core.models.photos_upload_path, verbose_name='Foto 02')),
                ('photo03', models.ImageField(null=True, upload_to=core.models.photos_upload_path, verbose_name='Foto 03')),
                ('photo04', models.ImageField(null=True, upload_to=core.models.photos_upload_path, verbose_name='Foto 04')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Forndecedor',
                'verbose_name_plural': 'Forndecedores',
            },
        ),
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('body', models.TextField(verbose_name='Comentário')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('accepted', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Produto relacionado')),
            ],
            options={
                'verbose_name': 'Comentário de Produto',
                'verbose_name_plural': 'Comentários de Produto',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Provider', verbose_name='Fornecedor'),
        ),
    ]
